### ISSUE TITLE
KeyError: '__getstate__'

### ISSUE THREAD

**Issue by KevinBaylor** [rishikksh20/hifigan-denoiser#4]
Hi, thanks for opensourcing your code! During the training process, I met an error with the command bellow.

**COMMAND**
python train.py -c config.yaml

**ERROR**
Initializing Training Process..
Batch size per GPU : 0
Traceback (most recent call last):
  File "train.py", line 304, in <module>
    main()
  File "train.py", line 298, in main
    mp.spawn(train, nprocs=hp.train.num_gpus, args=(args, hp, hp_str,))
  File "/home/lian/.conda/envs/hifi-GAN-denoise/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn') 
  File "/home/lian/.conda/envs/hifi-GAN-denoise/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 148, in start_processes
    process.start()
  File "/home/lian/.conda/envs/hifi-GAN-denoise/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/lian/.conda/envs/hifi-GAN-denoise/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/lian/.conda/envs/hifi-GAN-denoise/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/lian/.conda/envs/hifi-GAN-denoise/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/lian/.conda/envs/hifi-GAN-denoise/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/lian/.conda/envs/hifi-GAN-denoise/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
KeyError: '__getstate__'

Would you like to tell me why it happened and how to solve it? Thank you! Have a nice day.

**Comment by ReyraV** [comment]
I got this error when num_gpus was not equal to the number of available GPUs. To solve this problem, i added in the training code os.environ["CUDA_VISIBLE_DEVICES"]="0" because i had num_gpus=1.

**Comment by skol101** [comment]
Yep, doesn't work for multi gpu training.
